# Example of a workflow using some of these actions.
# The actual code in this repo is from the App Center

name: My Workflow

on:
  workflow_dispatch:
  push:


jobs:
  melos-matrix:
    uses: ./.github/workflows/melos-matrix.yaml
    with:
      os: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]

  standalone-melos:
    uses: ./.github/workflows/melos.yaml

  # Or if the repo doesn't use melos:
  # flutter-actions:
  #   uses: ./.github/workflows/flutter.yaml

  flutter-actions:
    uses: ./.github/workflows/flutter.yaml
    with:
      packages-dir: packages
